### ISSUE TITLE
asLong

### ISSUE THREAD

**Issue by benman1** [wnameless/json-flattener#1]
Thanks for your work on this great library. It seems very useful.

However, I am having a problem... 

My json looks like this (obfuscated): 
{"39473331":{"mega":6.0,"goals":1.0}}

and I am getting this exception: 

Caused by: java.lang.NumberFormatException: For input string: "6.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at com.eclipsesource.json.JsonNumber.asLong(JsonNumber.java:61)
	at com.github.wnameless.json.flattener.JsonFlattener.jsonVal2Obj(JsonFlattener.java:174)

Now I was looking at your code and I've seen this here: 

      double v = jsonValue.asDouble();
      if (!Double.isNaN(v) && !Double.isInfinite(v) && v == Math.rint(v))
        return jsonValue.asLong();
      else
        return jsonValue.asDouble();

Shouldn't it be the other way around? Like this: 
      if (!Double.isNaN(v) && !Double.isInfinite(v) && v == Math.rint(v))
        return v;
      else
        return jsonValue.asLong();

In any case, it shouldn't try to parse 6.0 as a long.

**Comment by wnameless** [comment]
Thanks for reporting! This bug is due to the misuse of minimal-json. I just fixed it and published into the new version 0.1.1.
