### ISSUE TITLE
Parse Exception

### ISSUE THREAD

**Issue by edwardkt** [wnameless/json-flattener#16]
I keep getting this error when I parse my file:

Exception in thread "main" com.eclipsesource.json.ParseException: Expected value at 1:0
	at com.eclipsesource.json.JsonParser.error(JsonParser.java:379)
	at com.eclipsesource.json.JsonParser.expected(JsonParser.java:372)
	at com.eclipsesource.json.JsonParser.readValue(JsonParser.java:108)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:73)
	at com.eclipsesource.json.Json.parse(Json.java:295)
	at com.github.wnameless.json.flattener.JsonFlattener.<init>(JsonFlattener.java:111)
	at com.github.wnameless.json.flattener.JsonFlattener.flatten(JsonFlattener.java:80)
	at Test.main(Test.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

The input I get is a new line delimited json, just an FYI

**Comment by wnameless** [comment]
Could u provide the input data?

**Comment by edwardkt** [comment]
i actually figured out the issue. sorry about that.

**Comment by alkesh26** [comment]
hey @edwardkt I am facing the same issue, can you please tell me the solution

**Comment by alkesh26** [comment]
figured out

**Comment by nenavathkrishna** [comment]
hey @edwardkt and @alkesh26 i am facing same issue, please tell me how you solved this issue.

**Comment by bhavana184** [comment]
hi @edwardkt , may I know what issue you found? I am also facing the same issue and unable to find the answer for the same. May be your solution can help. Thanks
