### ISSUE TITLE
flatten+ merge + unflatten

### ISSUE THREAD

**Issue by vanketesh-rapido** [wnameless/json-flattener#49]
Hi,

I am trying to flatten these 2 json combine then and unflatten them back but for some reason this error out 
`
String data = "{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce2\"},\"display\":{\"rider\":false,\"customer\":false},\"tax\":{\"igst\":{\"percent\":0},\"sgst\":{\"percent\":0},\"cgst\":{\"percent\":0}},\"areaId\":null,\"active\":true,\"snooze\":false,\"serviceType\":\"delivery\",\"lyte\":false,\"platformCharges\":0,\"insuranceCharges\":0,\"cancelCharge\":0,\"cancelChargeTime\":0,\"extra\":0,\"createdBy\":{\"$oid\":\"59c3b272faf04e0b36e6aeba\"},\"createdOn\":1.55195672524E12,\"lastModifiedBy\":null,\"lastModifiedOn\":1.551955213555E12,\"timings\":[{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce9\"},\"from\":0,\"to\":2359,\"weekDay\":0,\"operational\":true},{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce8\"},\"from\":0,\"to\":2359,\"weekDay\":1,\"operational\":true},{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce7\"},\"from\":0,\"to\":2359,\"weekDay\":2,\"operational\":true},{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce6\"},\"from\":0,\"to\":2359,\"weekDay\":3,\"operational\":true},{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce5\"},\"from\":0,\"to\":2359,\"weekDay\":4,\"operational\":true},{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce4\"},\"from\":0,\"to\":2359,\"weekDay\":5,\"operational\":true},{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce3\"},\"from\":0,\"to\":2359,\"weekDay\":6,\"operational\":true}],\"lyteData\":{\"timings\":[]},\"priceWithKm\":[{\"kms\":100,\"price\":0}],\"city\":{\"$oid\":\"5a5f70a81635168040c9a163\"},\"baseFare\":0,\"minimumFare\":0,\"pricePerKm\":0,\"pricePerMinute\":0,\"rule\":\"0\",\"service\":{\"$oid\":\"58dcea3824565ce21202bca3\"},\"__v\":0,\"captain\":{\"regular\":{\"baseFare\":0,\"minimumFare\":0,\"pricePerMinute\":0,\"rule\":\"0\",\"priceWithKm\":[{\"kms\":100,\"price\":0}]}}} "`

        
`String sortedPatches = "{\"baseFare\":30,\"batchable\":false,\"captain\":{\"regular\":{\"baseFare\":0,\"minimumFare\":0,\"pricePerMinute\":0,\"rule\":\"0\",\"priceWithKm\":[{\"kms\":5,\"price\":0},{\"kms\":100,\"price\":0}]},\"batch\":{\"first\":{\"priceWithKm\":[]},\"next\":{\"priceWithKm\":[]}}},\"customer\":{\"batch\":{\"first\":{\"cancelCharge\":{\"ratePerKm\":[]},\"priceWithKm\":[]},\"next\":{\"cancelCharge\":{\"ratePerKm\":[]},\"priceWithKm\":[]}}},\"lastModifiedBy\":{\"$oid\":\"59c3b272faf04e0b36e6aeba\"},\"lastModifiedOn\":1.597231063793E12,\"minimumFare\":30,\"priceWithKm\":[{\"_id\":{\"$oid\":\"5f33cfd76e388d4ea5f570dc\"},\"kms\":5,\"price\":0},{\"_id\":{\"$oid\":\"5f33cfd76e388d7f57f570db\"},\"kms\":100,\"price\":4}],\"staticSurgeToCaptain\":false}";`

error :
```
Exception in thread "main" java.lang.UnsupportedOperationException: Not an object: null
	at com.eclipsesource.json.JsonValue.asObject(JsonValue.java:290)
	at com.github.wnameless.json.unflattener.JsonUnflattener.setUnflattenedValue(JsonUnflattener.java:390)
	at com.github.wnameless.json.unflattener.JsonUnflattener.unflatten(JsonUnflattener.java:272)
	at com.github.wnameless.json.unflattener.JsonUnflattener.unflatten(JsonUnflattener.java:58)
```

Although both the json after unflattening indivisually look fine it is when i merge them and unflatten code errors out.

**Comment by vanketesh-rapido** [comment]
update validated the output here https://jsfiddle.net/S2hsS/ and final string that has to be unflattened works right.
don't know whats the issue here

**Comment by wnameless** [comment]
I've written a little tester with v0.9.0, and there was no exception. Can you provide your testing code? 

```java
  public static void main(String[] args)
      throws JsonMappingException, JsonProcessingException {
    String data =
        "{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce2\"},\"display\":{\"rider\":false,\"customer\":false},\"tax\":{\"igst\":{\"percent\":0},\"sgst\":{\"percent\":0},\"cgst\":{\"percent\":0}},\"areaId\":null,\"active\":true,\"snooze\":false,\"serviceType\":\"delivery\",\"lyte\":false,\"platformCharges\":0,\"insuranceCharges\":0,\"cancelCharge\":0,\"cancelChargeTime\":0,\"extra\":0,\"createdBy\":{\"$oid\":\"59c3b272faf04e0b36e6aeba\"},\"createdOn\":1.55195672524E12,\"lastModifiedBy\":null,\"lastModifiedOn\":1.551955213555E12,\"timings\":[{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce9\"},\"from\":0,\"to\":2359,\"weekDay\":0,\"operational\":true},{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce8\"},\"from\":0,\"to\":2359,\"weekDay\":1,\"operational\":true},{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce7\"},\"from\":0,\"to\":2359,\"weekDay\":2,\"operational\":true},{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce6\"},\"from\":0,\"to\":2359,\"weekDay\":3,\"operational\":true},{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce5\"},\"from\":0,\"to\":2359,\"weekDay\":4,\"operational\":true},{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce4\"},\"from\":0,\"to\":2359,\"weekDay\":5,\"operational\":true},{\"_id\":{\"$oid\":\"5c80faf5563c541acb178ce3\"},\"from\":0,\"to\":2359,\"weekDay\":6,\"operational\":true}],\"lyteData\":{\"timings\":[]},\"priceWithKm\":[{\"kms\":100,\"price\":0}],\"city\":{\"$oid\":\"5a5f70a81635168040c9a163\"},\"baseFare\":0,\"minimumFare\":0,\"pricePerKm\":0,\"pricePerMinute\":0,\"rule\":\"0\",\"service\":{\"$oid\":\"58dcea3824565ce21202bca3\"},\"__v\":0,\"captain\":{\"regular\":{\"baseFare\":0,\"minimumFare\":0,\"pricePerMinute\":0,\"rule\":\"0\",\"priceWithKm\":[{\"kms\":100,\"price\":0}]}}} ";
    String sortedPatches =
        "{\"baseFare\":30,\"batchable\":false,\"captain\":{\"regular\":{\"baseFare\":0,\"minimumFare\":0,\"pricePerMinute\":0,\"rule\":\"0\",\"priceWithKm\":[{\"kms\":5,\"price\":0},{\"kms\":100,\"price\":0}]},\"batch\":{\"first\":{\"priceWithKm\":[]},\"next\":{\"priceWithKm\":[]}}},\"customer\":{\"batch\":{\"first\":{\"cancelCharge\":{\"ratePerKm\":[]},\"priceWithKm\":[]},\"next\":{\"cancelCharge\":{\"ratePerKm\":[]},\"priceWithKm\":[]}}},\"lastModifiedBy\":{\"$oid\":\"59c3b272faf04e0b36e6aeba\"},\"lastModifiedOn\":1.597231063793E12,\"minimumFare\":30,\"priceWithKm\":[{\"_id\":{\"$oid\":\"5f33cfd76e388d4ea5f570dc\"},\"kms\":5,\"price\":0},{\"_id\":{\"$oid\":\"5f33cfd76e388d7f57f570db\"},\"kms\":100,\"price\":4}],\"staticSurgeToCaptain\":false}";

    ObjectMapper mapper = new ObjectMapper();
    ObjectNode dataON = (ObjectNode) mapper.readTree(data);
    ObjectNode sortedPatchesON = (ObjectNode) mapper.readTree(sortedPatches);

    dataON.setAll(sortedPatchesON);

    String flattenJson = JsonFlattener.flatten(dataON.toPrettyString());
    System.out.println(flattenJson);
    System.out.println(JsonUnflattener.unflatten(flattenJson));
  }
```

**Comment by vanketesh-rapido** [comment]
This is what I was working with
```

import com.github.wnameless.json.flattener.JsonFlattener;
import com.github.wnameless.json.unflattener.JsonUnflattener;

import java.util.*;
import java.util.regex.Pattern;

public class JsonFlattnerUpdate {

    public static void main(String[] args) throws Exception{


        String data = "{\"_id\":{\"$oid\":\"5f34ca7a8cba7e0007dc605a\"},\"location\":{\"lat\":0,\"lng\":0,\"cluster\":\"\",\"city\":\"\",\"state\":\"\",\"zipcode\":0,\"address\":\"\"},\"gst\":{\"approved\":false,\"gstNumber\":\"\"},\"statusUpdates\":{\"activatedBy\":null,\"deActivatedBy\":null,\"reActivatedBy\":null},\"createdOn\":1.597295226164E12,\"lastModifiedOn\":1.597295226164E12,\"ordersCount\":0,\"sendInvoice\":false,\"name\":\"\",\"ownerName\":\"\",\"email\":\"\",\"pan\":\"\",\"creditLimit\":0,\"accountManager\":\"\",\"status\":\"inactive\",\"clientId\":{\"$oid\":\"5f34ca7aadf4f800091add45\"},\"channelInfo\":{\"channelName\":\"app\",\"channelHost\":\"android\",\"channelEntity\":\"merchant\"},\"device\":{\"deviceId\":\"869447038498146\"},\"firebaseToken\":\"eb7VeS7FTOmvfZTrbR6q0b:APA91bEFmk6QdZkzFkewK2QcEEglpYxkRUd_UlqlfPMgBdB_69jSyKLUzHJa6p2rpJK7UwwRE5r_p49HeyDaFhEktM9_uPATn6wdt9D31kZA6EQm20VJAtmzejDrm9r-67XbJpRfJKnv\",\"mobile\":\"8508451901\",\"provider\":\"local\",\"registeredDate\":\"2020-08-13\",\"services\":[],\"__v\":0}";
        /*String sortedPatches = "[{\"progress.0.coinsExpiryReferred\": null,\"progress.1.coinsExpiryReferred\":null,\"progress.0.status\": \"CREDITED\",\"progress.0.timestamp\": 1.595434203832E12,\"updatedAt\": {\"$date\": 1595434203833}}]";*/
        String sortedPatches = "[{\"lastModifiedOn\":1.597295303645E12,\"location\":{\"lat\":10.9987122,\"lng\":76.9789362,\"cluster\":\"Gandhipuram\",\"city\":\"Coimbatore\",\"address\":\"32-A 1st Floor, Race Course Rd, Mamarath Thottom Ganapathy, Race Course, Coimbatore, Tamil Nadu 641018, India\"},\"name\":\"Red door cafe \",\"ownerName\":\"Thirunayanam\"}, {\"email\":\"mahesekar98@gmail.com\",\"lastModifiedOn\":1.597295328016E12}, {\"lastModifiedOn\":1.597295329522E12}, {\"lastModifiedOn\":1.597295356664E12,\"status\":\"active\",\"statusUpdates.activatedBy\":{\"$oid\":\"5c57e783cf348960d821cf88\"},\"statusUpdates.activatedOn\":1.597295356663E12}]";


        String empty = "{}";
        String finalJsonAfterUpdate = new String();
            Map<String, Object> flattenJsondata = JsonFlattener.flattenAsMap(data);
            System.out.println(flattenJsondata.toString());
            String updateformatted = sortedPatches.substring(1, sortedPatches.length() - 1).replaceAll("\\s+", "").replace("},{", ",");
            //logger.info(updateformatted);
            Map<String, Object> flattenJsonsortedObjects = JsonFlattener.flattenAsMap(updateformatted);

            Map<String, Object> aptUpdatesFlattened = JsonFlattener.flattenAsMap(empty);
            for (Map.Entry<String, Object> entry : flattenJsonsortedObjects.entrySet()) {
                String entries = entry.getKey().replace("\\", "").replace("\"", "").replaceAll("\\[(.*?)\\]", ".$1");
                List<String> members = Arrays.asList(entries.split("\\."));
                String preparedKey = new String();
                for (String member : members) {
                    if (Pattern.matches("[0-9]", member)) {
                        preparedKey = preparedKey.concat("[" + member + "]");
                    } else {
                        preparedKey = preparedKey.concat("." + member);
                    }

                }
                preparedKey = preparedKey.substring(1);
                //System.out.println(entry.getKey());
                //System.out.println("-->"+preparedKey);
                aptUpdatesFlattened.put(preparedKey, entry.getValue());

            }
            System.out.println("flattenJsondata before" + flattenJsondata);
            flattenJsondata.putAll(aptUpdatesFlattened);
            //System.out.println("aptUpdatesFlattened "+aptUpdatesFlattened);
            System.out.println("flattenJsondata"+flattenJsondata);
            finalJsonAfterUpdate = JsonUnflattener.unflatten(flattenJsondata.toString());
            System.out.println(finalJsonAfterUpdate);

    }
}
```

**Comment by vanketesh-rapido** [comment]
Any update on this ?

**Comment by wnameless** [comment]
The error is caused by those 2 lines:

"statusUpdates.activatedBy":null
".statusUpdates.activatedBy.$oid":"5c57e783cf348960d821cf88"

According to the first line, activatedBy is assigned as a null Json object, therefore $oid cannot be inserted.
BTW, the first dot(.) in the second line is unaccepted as well.

**Comment by vanketesh-rapido** [comment]
@wnameless are planning to add support for this in future. When outer object is null and a child object gets added with some value ?
